exclude: "^(doc)|(cookiecutters)"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: double-quote-string-fixer
      - id: forbid-new-submodules

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        name: yapf
        types: [python]
        args: ["-i"]
        additional_dependencies: ["toml"]

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort

  - repo: https://github.com/ikamensh/flynt/
    rev: "0.77"
    hooks:
      - id: flynt
        args: ["--line-length=120", "--fail-on-change"]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        types: [python]
        language: system
        exclude: |
          (?x)(
          ^examples/
          )
